@SkiService_HostAddress = http://localhost:5231/swagger
### Authentifizierung
### Login für JWT-Token

POST http://localhost:5231/api/Auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "password"
}


### Alle Serviceaufträge abrufen
GET http://localhost:5231/api/Order/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImp0aSI6IjNiNjNmY2M1LWM0N2MtNGI0Yy04MWQ0LWRmZjNjODVmNGM2OSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzM2OTU1MjI1fQ.fBqQTPdMLERAwl8SVQ4b78hQkew0MA2GEeQCAQAi38M
---

### Einen spezifischen Serviceauftrag anhand der ID abrufen
GET http://localhost:5231/api/Order/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImp0aSI6IjNiNjNmY2M1LWM0N2MtNGI0Yy04MWQ0LWRmZjNjODVmNGM2OSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzM2OTU1MjI1fQ.fBqQTPdMLERAwl8SVQ4b78hQkew0MA2GEeQCAQAi38M

---

### Einen bestehenden Serviceauftrag anhand der ID aktualisieren
PUT http://localhost:5231/api/Order/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImp0aSI6IjNiNjNmY2M1LWM0N2MtNGI0Yy04MWQ0LWRmZjNjODVmNGM2OSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzM2OTU1MjI1fQ.fBqQTPdMLERAwl8SVQ4b78hQkew0MA2GEeQCAQAi38M
Content-Type: application/json

{
    "id": 2,
    "customerName": "Anna Schmidt",
    "email": "anna.schmidt@example.com",
    "phone": "0987654321",
    "priority": "Express",
    "status": "Completed",
    "serviceId": 3
}


### Einen neuen Serviceauftrag erstellen

POST  http://localhost:5231/api/Order/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImp0aSI6IjNiNjNmY2M1LWM0N2MtNGI0Yy04MWQ0LWRmZjNjODVmNGM2OSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzM2OTU1MjI1fQ.fBqQTPdMLERAwl8SVQ4b78hQkew0MA2GEeQCAQAi38M
Content-Type: application/json

{
    "CustomerName": "heu wilamus",
    "Email": "heu.wilamus@example.com",
    "Phone": "123456789",
    "Priority": "Express",
    "Status": "Pending",
    "ServiceId": 6
}

### Einen Serviceauftrag anhand der ID löschen
DELETE http://localhost:5231/api/Order/8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImp0aSI6IjkyYjI2YjFkLTgyZjItNDkzNS05MDUyLThlYWIzYjc2YzU1MSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzM2OTM2NzU5fQ.OSvyEp2aaiPc10_V_ZxTT-djTa4QeO4q5Jt83zSU4zQ
